import { Metadata } from 'next';
import Breadcrumbs from '../../components/ui/Breadcrumbs';

export const metadata: Metadata = {
  title: 'Disclaimer | AgePulse',
  description: 'Legal disclaimer regarding calculation accuracy and usage for AgePulse.',
  alternates: {
    canonical: '/disclaimer',
  },
};

export default function DisclaimerPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12 space-y-6 text-slate-800 dark:text-slate-200">
      <Breadcrumbs items={[{ label: 'Disclaimer' }]} />

      <h1 className="text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight">
        Disclaimer
      </h1>
      <p className="text-xs text-slate-500 font-mono">Last updated: August 13, 2026</p>

      <section className="space-y-4 text-sm leading-relaxed">
        <h2 className="text-xl font-bold text-slate-900 dark:text-white">1. Informational Purpose Only</h2>
        <p>
          The tools and calculations provided by AgePulse are designed strictly for general informational, educational, and entertainment purposes. While we strive for 100% mathematical accuracy using standard Gregorian calendar rules, results should not be relied upon as binding legal proof of age in court proceedings or official statutory contexts without independent verification.
        </p>

        <h2 className="text-xl font-bold text-slate-900 dark:text-white">2. No Legal or Financial Advice</h2>
        <p>
          Calculations generated by AgePulse do not constitute legal, tax, medical, or official government documentation.
        </p>

        <h2 className="text-xl font-bold text-slate-900 dark:text-white">3. Limitation of Liability</h2>
        <p>
          Under no circumstances shall AgePulse or its owners be liable for any direct, indirect, incidental, or consequential damages resulting from the use of or inability to use our calculation tools.
        </p>
      </section>
    </div>
  );
}
